In [ ]:
import torch
import numpy as np

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [ ]:
a = torch.FloatTensor
a

torch.FloatTensor

In [ ]:
a = torch.randint(-6,6, (3,4,5))
a

tensor([[[-5, -1, -3, -3, -2],
         [-5, -3,  2, -6,  2],
         [-3,  5, -5, -6,  5],
         [-2, -2,  4,  4,  1]],

        [[ 0, -6, -1,  3,  0],
         [ 5,  3, -5,  4,  1],
         [-5, -4,  1,  1, -6],
         [-2,  4,  2, -6, -6]],

        [[-4,  5,  2,  2,  0],
         [ 3, -3, -5,  3, -4],
         [ 4,  2,  4, -3, -3],
         [ 4, -2,  2,  4, -4]]])

In [ ]:
# 2. Выведите его форму (shape)

In [ ]:
a.shape

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10

In [ ]:
a = a.reshape(6,10)
print(a.shape)
a

torch.Size([6, 10])


tensor([[-5, -1, -3, -3, -2, -5, -3,  2, -6,  2],
        [-3,  5, -5, -6,  5, -2, -2,  4,  4,  1],
        [ 0, -6, -1,  3,  0,  5,  3, -5,  4,  1],
        [-5, -4,  1,  1, -6, -2,  4,  2, -6, -6],
        [-4,  5,  2,  2,  0,  3, -3, -5,  3, -4],
        [ 4,  2,  4, -3, -3,  4, -2,  2,  4, -4]])

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [ ]:
b = torch.IntTensor
b = torch.randint(-2,3, (1,10))
print(b.shape)
b

torch.Size([1, 10])


tensor([[ 2, -1, -1,  1,  0, -2, -2, -1, -2,  1]])

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [ ]:
c = a.mul(b)
c

tensor([[-10,   1,   3,  -3,   0,  10,   6,  -2,  12,   2],
        [ -6,  -5,   5,  -6,   0,   4,   4,  -4,  -8,   1],
        [  0,   6,   1,   3,   0, -10,  -6,   5,  -8,   1],
        [-10,   4,  -1,   1,   0,   4,  -8,  -2,  12,  -6],
        [ -8,  -5,  -2,   2,   0,  -6,   6,   5,  -6,  -4],
        [  8,  -2,  -4,  -3,   0,  -8,   4,  -2,  -8,  -4]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [ ]:
torch.matmul(c, c.reshape(-1,6))

tensor([[ -71,  -73,  148,  -16, -121, -170],
        [  87,   -8,  -94,   10,   12,  -77],
        [ 203,   -9,  -50,   44,   73,   10],
        [  67,   17,  -10,   92,   25,  -79],
        [  62,   46,  -70,  -34,   62,  -36],
        [  12,   53,  -24,  -58,   13,   75]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [ ]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = x**3 + z - 75*t
y.backward(x)
print(x.grad)

tensor(3.)


In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [ ]:
f = torch.ones(5,6)
f

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. Переведите его в формат numpy

In [ ]:
f = f.numpy()
f

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)